<a href="https://colab.research.google.com/github/VirGonzalez/IA_/blob/main/Virginia_Gonzalez_TP_Reglas_de_asociaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cargamos la librerÃ­a que nos permite acceder al dataset

In [151]:
# soporte para cargar dataset de https://www.openml.org/
!pip install openml
import openml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openml in /usr/local/lib/python3.9/dist-packages (0.13.1)
Requirement already satisfied: liac-arff>=2.4.0 in /usr/local/lib/python3.9/dist-packages (from openml) (2.5.0)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.9/dist-packages (from openml) (1.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from openml) (2.27.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from openml) (2.8.2)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.9/dist-packages (from openml) (1.10.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from openml) (1.5.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.9/dist-packages (from openml) (9.0.0)
Requirement already satisfied: numpy>=1.6.2 in /usr/local/lib/python3.9/dist-packages (from openml) (1.22.4)
Requirement already satisfied: minio in /usr/local/lib/python3.9/dist-packages (from openml) (7.1.14)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.9/dist-packages (from openml) (0.13.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->openml) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil->openml) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.18->openml) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.18->openml) (3.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from minio->openml) (2022.12.7)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from minio->openml) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->openml) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->openml) (3.4)

Accedemos al dataset

In [152]:
import pandas as pd

# indicamos cual dataset queremos utilizar, en este caso el nro. 24
dataset = openml.datasets.get_dataset(24)

# separamos las informaciÃ³n almacenada en el dataset
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format='dataframe',
    target=dataset.default_target_attribute
)

#  concatenamos la informaciÃ³n relevante en un Ãºnico DataFrame 
df = pd.concat([X, y], axis=1)
df

,cap-shape,cap-surface,cap-color,bruises%3F,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,class
0,x,s,n,t,p,f,c,n,k,e,...,w,w,p,w,o,p,k,s,u,p
1,x,s,y,t,a,f,c,b,k,e,...,w,w,p,w,o,p,n,n,g,e
2,b,s,w,t,l,f,c,b,n,e,...,w,w,p,w,o,p,n,n,m,e
3,x,y,w,t,p,f,c,n,n,e,...,w,w,p,w,o,p,k,s,u,p
4,x,s,g,f,n,f,w,b,k,t,...,w,w,p,w,o,e,n,a,g,e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,k,s,n,f,n,a,c,b,y,e,...,o,o,p,o,o,p,b,c,l,e
8120,x,s,n,f,n,a,c,b,y,e,...,o,o,p,n,o,p,b,v,l,e
8121,f,s,n,f,n,a,c,b,n,e,...,o,o,p,o,o,p,b,c,l,e
8122,k,y,n,f,y,f,c,n,b,t,...,w,w,p,w,o,e,w,v,l,p
8123,x,s,n,f,n,a,c,b,y,e,...,o,o,p,o,o,p,o,c,l,e

In [153]:
df.columns

Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises%3F', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat', 'class'],
      dtype='object')

In [154]:
df = df[['population', 'habitat']]
df

     population habitat
0             s       u
1             n       g
2             n       m
3             s       u
4             a       g
...         ...     ...
8119          c       l
8120          v       l
8121          c       l
8122          v       l
8123          c       l

[8124 rows x 2 columns]

In [155]:
df_dummies = pd.get_dummies(df, prefix=['pop', 'hab'],columns=['population', 'habitat'])
df_dummies

,pop_a,pop_c,pop_n,pop_s,pop_v,pop_y,hab_d,hab_g,hab_l,hab_m,hab_p,hab_u,hab_w
0,0,0,0,1,0,0,0,0,0,0,0,1,0
1,0,0,1,0,0,0,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,1,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,1,0,0,0,0,0,0,1,0,0,0,0
8120,0,0,0,0,1,0,0,0,1,0,0,0,0
8121,0,1,0,0,0,0,0,0,1,0,0,0,0
8122,0,0,0,0,1,0,0,0,1,0,0,0,0
8123,0,1,0,0,0,0,0,0,1,0,0,0,0

**Objetivo**

El objetivo de este trabajo sera determinar si existe una relacion entre el habitat y la disposicion de la poblacion debido a la interaccion con compuestos quimicos del ambiente. El microbioma de la atmosfera puede afectar al hongo y a traves de este trabajo buscaremos dilucidar si existe un efecto del habitat.
Espero encontrar que en aquellos habitats mas disturbados como urbanos la disposicion de los hongos sera mas agregada, mientras en bosque y pastizales expandiran su area de ocupacion

In [156]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(df_dummies).transform(df_dummies)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,_,a,b,c,d,g,h,l,m,n,o,p,s,u,v,w,y
0,True,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
1,True,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8120,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8121,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8122,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8123,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [157]:
from mlxtend.frequent_patterns import apriori

apriori(df , min_support=0.1,use_colnames=True)

/usr/local/lib/python3.9/dist-packages/mlxtend/frequent_patterns/apriori.py:158: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  itemsets = pd.Series([frozenset(i) for i in itemset_dict[k]])

Empty DataFrame
Columns: [support, itemsets]
Index: []